env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "import/extensions": "off",
  "react/jsx-filename-extension": [1, { "extensions": [".tsx", ".ts"] }],
  "no-return-assign": "off",
  "no-case-declarations": "off"
}
settings:
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
